server:
  port: 9030
swagger:
  title: ${spring.application.name}
spring:
  datasource:
    url: jdbc:mysql://leemay.cn:3306/leemay_mall?characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: ajin
    password: Spring.222
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl