spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        cors-configurations: # 跨域配置
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" # 跨域处理,允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: mall-sys-app-goods # 唯一标识
          uri: lb://mall-sys-app-goods # 请求要路由的服务
          predicates:
            - Path=/sys/goods/**
          filters:
            - StripPrefix= 1
  #            - name: RequestRateLimiter # 请求数限流,名字不能随便写
  #              args:
  #                key-resolver: "#{@ipKeyResolver}" # 引用bean
  #                redis-rate-limiter.replenishRate: 1 # 令牌桶每秒填充平均速率
  #                redis-rate-limiter.burstCapacity: 1 # 令牌桶总容量
  redis:
    host: localhost