server:
  port: 8010
swagger:
  title: ${spring.application.name}
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/a?characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat,wall,log4j2
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connect-properties:
        druid:
          stat:
            mergeSql: true
            slowSqlMillis: 500
      stat-view-servlet:
        login-username: root # 后台监控登录账号
        login-password: root1024 # 后台监控登录密码
        enabled: true # 是否开启后台监控
  redis:
    host: localhost
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
repeat:
  interval-time: 8000 # 重复提交，间隔时间（毫秒）
logging:
  config: classpath:log/log4j2-dev.xml