server:
  port: 9020
spring:
  application:
    name: searchService
swagger:
  desc: "fjdkls"
  title: ${spring.application.name}
es:
  host: 121.43.140.160
  port: 9200
  scheme: http
  index: index-test
