server:
  port: 9020
swagger:
  title: ${spring.application.name}
es:
  host: 192.168.1.128
  port: 9200
  scheme: http
  index: index-test
spring:
  datasource:
    url: jdbc:mysql://leemay.cn:3306/leemay_mall?characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: ajin
    password: Spring.222
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver